import './logger.js';
import './config.js';
import './state.js';
import './audio.js';
import './request.js';
import './walletconnect.js';
import './assets.js';
import './particles.js';
import './perf.js';
import './security.js';
import './auth.js';
import './api.js';
import './ui.js';
import './store.js';
import './physics.js';
import './renderer.js';
import './input.js';
import { stabilizeMenuLoad } from './stabilize-menu.js';
import './game.js';

stabilizeMenuLoad();
