const INNER_RADIUS_RATIO = 0.15;
const MOUTH_EXTENSION_DEPTH = 2.4;
const LANE_ANGLE_STEP = 0.55;
const TRACK_LANE_CENTERS = Object.freeze([-1, 0, 1]);
const TRACK_SLAT_PERIOD = 2.9;
const TRACK_SLAT_LENGTH = 0.82;
const TRACK_SLAT_SOFTNESS = 0.22;
const TRACK_SLAT_ALPHA_MULTIPLIER = 0.16;
const GRID_ALPHA_MULTIPLIER = 0.2;
const GRID_AMBIENT_ALPHA_FLOOR = 0.05;
const GRID_AMBIENT_DEPTH_BOOST = 0.03;
const GRID_COLOR_NEAR = 0xc7e6ff;
const GRID_COLOR_FAR = 0x6ea8dd;
const GRID_RADIAL_LINE_WIDTH = 1.05;
const GRID_RING_LINE_WIDTH = 0.85;
const GRID_RADIAL_GLOW_LINE_WIDTH = 2.4;
const GRID_RING_GLOW_LINE_WIDTH = 2;
const GRID_GLOW_ALPHA_MULTIPLIER = 0.42;
const GRID_MIN_VISIBILITY_ALPHA = 0.01;
const SPEED_STREAK_COLORS = Object.freeze([0xff5ff5, 0xffffff, 0x51fff2]);
const SPEED_STREAK_MIN_DEPTH_RATIO = 0.12;
const SPEED_STREAK_MAX_DEPTH_RATIO = 0.92;
const SPEED_STREAK_BASE_ALPHA = 0.018;
const SPEED_STREAK_MAX_ALPHA = 0.11;
const SPEED_STREAK_WIDTH_RATIO = 0.22;
const PERIODIC_STRIPE_COLORS = Object.freeze([0xff5a1f, 0xfff6e8, 0xff7d33]);
const PERIODIC_STRIPE_ANGLE_REPEAT = 9;
const PERIODIC_STRIPE_ANGLE_WIDTH = 0.19;
const PERIODIC_STRIPE_PERIOD = 3.6;
const PERIODIC_STRIPE_LENGTH = 1.1;
const PERIODIC_STRIPE_SOFTNESS = 0.4;
const PERIODIC_STRIPE_BASE_ALPHA = 0.04;
const PERIODIC_STRIPE_MAX_ALPHA = 0.38;
const PERIODIC_STRIPE_RAY_LINE_WIDTH = 1.25;
const PERIODIC_STRIPE_RAY_GLOW_LINE_WIDTH = 3.4;
const PERIODIC_STRIPE_RAY_SPARSE_NOISE_THRESHOLD = 0.62;
const QUALITY_PRESETS = Object.freeze({
  low: {
    depthStep: 3,
    segmentStep: 2,
    segmentAlpha: 0.9,
  },
  medium: {
    depthStep: 2,
    segmentStep: 1,
    segmentAlpha: 0.92,
  },
  high: {
    depthStep: 1,
    segmentStep: 1,
    segmentAlpha: 0.95,
  },
});

export {
  GRID_ALPHA_MULTIPLIER,
  GRID_AMBIENT_ALPHA_FLOOR,
  GRID_AMBIENT_DEPTH_BOOST,
  GRID_COLOR_FAR,
  GRID_COLOR_NEAR,
  GRID_GLOW_ALPHA_MULTIPLIER,
  GRID_MIN_VISIBILITY_ALPHA,
  GRID_RADIAL_GLOW_LINE_WIDTH,
  GRID_RADIAL_LINE_WIDTH,
  GRID_RING_GLOW_LINE_WIDTH,
  GRID_RING_LINE_WIDTH,
  INNER_RADIUS_RATIO,
  LANE_ANGLE_STEP,
  MOUTH_EXTENSION_DEPTH,
  PERIODIC_STRIPE_ANGLE_REPEAT,
  PERIODIC_STRIPE_ANGLE_WIDTH,
  PERIODIC_STRIPE_BASE_ALPHA,
  PERIODIC_STRIPE_COLORS,
  PERIODIC_STRIPE_LENGTH,
  PERIODIC_STRIPE_MAX_ALPHA,
  PERIODIC_STRIPE_PERIOD,
  PERIODIC_STRIPE_RAY_GLOW_LINE_WIDTH,
  PERIODIC_STRIPE_RAY_LINE_WIDTH,
  PERIODIC_STRIPE_RAY_SPARSE_NOISE_THRESHOLD,
  PERIODIC_STRIPE_SOFTNESS,
  QUALITY_PRESETS,
  SPEED_STREAK_BASE_ALPHA,
  SPEED_STREAK_COLORS,
  SPEED_STREAK_MAX_ALPHA,
  SPEED_STREAK_MAX_DEPTH_RATIO,
  SPEED_STREAK_MIN_DEPTH_RATIO,
  SPEED_STREAK_WIDTH_RATIO,
  TRACK_LANE_CENTERS,
  TRACK_SLAT_ALPHA_MULTIPLIER,
  TRACK_SLAT_LENGTH,
  TRACK_SLAT_PERIOD,
  TRACK_SLAT_SOFTNESS,
};
